######################################################################
# Automatically generated by qmake (2.01a) Sun May 5 15:19:37 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += GameplayWindow.h MainWindow.h NameWidget.h ScoreDoc.h
SOURCES += GameplayWindow.cpp \
           main.cpp \
           MainWindow.cpp \
           NameWidget.cpp \
           ScoreDoc.cpp
