######################################################################
# Automatically generated by qmake (2.01a) Sat May 4 17:01:14 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += GameplayWindow.h MainWindow.h NameWidget.h
SOURCES += GameplayWindow.cpp main.cpp MainWindow.cpp NameWidget.cpp
